### ISSUE TITLE
Python questions

### ISSUE THREAD

**Issue by dlanghorne0428** [pal1000/save-legacy-intel-opengl#1]
I apologize for opening an issue, but I didn't see another way to contact you. 
I saw your Youtube video on fixing OpenGL support for Java.
I know someone with an HD 3000 graphics adapter who is having OpenGL problems with Python.

My questions are:
1) Looking at the python.cmd file, if the machine is 64-bit architecture, fixes are applied to both 32-bit and 64-bit versions of Python? What if only one version of Python is installed?
2) I assume the Application Compatibility Toolkit needs to be installed before running the .cmd file?

Thanks!

**Comment by pal1000** [comment]
No worries, contacting me by opening an issue is the expected approach. Now  regarding your questions.
1. If you only have either 32-bit or 64-bit Python 3.x, the fix for the one you don't have will be standby. If at a latter date you decide to install it, it will be already fixed.
2. Application Compatibility Toolkit is not needed to run the cmd files. Windows comes by default with everything needed to install SDB fixes.  Application Compatibility Toolkit is only needed for developing fixes.

**Comment by dlanghorne0428** [comment]
Thank you. This solution worked for my student.

**Comment by pal1000** [comment]
I updated the readme to include information about questions. With this being said I close this issue.
